export const states = [
    { name: "Alabama", abr: "AL" },
    { name: "Alaska", abr: "AK" },
    { name: "Arizona", abr: "AZ" },
    { name: "Arkansas", abr: "AR" },
    { name: "California", abr: "CA" },
    { name: "Canal Zone", abr: "CZ" },
    { name: "Colorado", abr: "CO" },
    { name: "Connecticut", abr: "CT" },
    { name: "Delaware", abr: "DE" },
    { name: "District of Columbia", abr: "DC" },
    { name: "Florida", abr: "FL" },
    { name: "Georgia", abr: "GA" },
    { name: "Guam", abr: "GU" },
    { name: "Hawaii", abr: "HI" },
    { name: "Idaho", abr: "ID" },
    { name: "Illinois", abr: "IL" },
    { name: "Indiana", abr: "IN" },
    { name: "Iowa", abr: "IA" },
    { name: "Kansas", abr: "KS" },
    { name: "Kentucky", abr: "KY" },
    { name: "Louisiana", abr: "LA" },
    { name: "Maine", abr: "ME" },
    { name: "Maryland", abr: "MD" },
    { name: "Massachusetts", abr: "MA" },
    { name: "Michigan", abr: "MI" },
    { name: "Minnesota", abr: "MN" },
    { name: "Mississippi", abr: "MS" },
    { name: "Missouri", abr: "MO" },
    { name: "Montana", abr: "MT" },
    { name: "Nebraska", abr: "NE" },
    { name: "Nevada", abr: "NV" },
    { name: "New Hampshire", abr: "NH" },
    { name: "New Jersey", abr: "NJ" },
    { name: "New Mexico", abr: "NM" },
    { name: "New York", abr: "NY" },
    { name: "North Carolina", abr: "NC" },
    { name: "North Dakota", abr: "ND" },
    { name: "Ohio", abr: "OH" },
    { name: "Oklahoma", abr: "OK" },
    { name: "Oregon", abr: "OR" },
    { name: "Pennsylvania", abr: "PA" },
    { name: "Puerto Rico", abr: "PR" },
    { name: "Rhode Island", abr: "RI" },
    { name: "South Carolina", abr: "SC" },
    { name: "South Dakota", abr: "SD" },
    { name: "Tennessee", abr: "TN" },
    { name: "Texas", abr: "TX" },
    { name: "Utah", abr: "UT" },
    { name: "Vermont", abr: "VT" },
    { name: "Virgin Islands", abr: "VI" },
    { name: "Virginia", abr: "VA" },
    { name: "Washington", abr: "WA" },
    { name: "West Virginia", abr: "WV" },
    { name: "Wisconsin", abr: "WI" },
    { name: "Wyoming", abr: "WY"  }
]

export const countries = [
    { name: "Afghanistan" },
    { name: "Albania" },
    { name: "Algeria" },
    { name: "Andorra" },
    { name: "Angola" },
    { name: "Antigua and Barbuda" },
    { name: "Argentina" },
    { name: "Armenia" },
    { name: "Australia" },
    { name: "Austria" },
    { name: "Azerbaijan" },
    { name: "Bahamas" },
    { name: "Bahrain" },
    { name: "Bangladesh" },
    { name: "Barbados" },
    { name: "Belarus" },
    { name: "Belgium" },
    { name: "Belize" },
    { name: "Benin" },
    { name: "Bhutan" },
    { name: "Bolivia" },
    { name: "Bosnia and Herzegovina" },
    { name: "Botswana" },
    { name: "Brazil" },
    { name: "Brunei" },
    { name: "Bulgaria" },
    { name: "Burkina Faso" },
    { name: "Burundi" },
    { name: "Côte d'Ivoire" },
    { name: "Cabo Verde" },
    { name: "Cambodia" },
    { name: "Cameroon" },
    { name: "Canada" },
    { name: "Central African Republic" },
    { name: "Chad" },
    { name: "Chile" },
    { name: "China" },
    { name: "Colombia" },
    { name: "Comoros" },
    { name: "Congo (Congo-Brazzaville)" },
    { name: "Costa Rica" },
    { name: "Croatia" },
    { name: "Cuba" },
    { name: "Cyprus" },
    { name: "Czechia (Czech Republic)" },
    { name: "Democratic Republic of the Congo" },
    { name: "Denmark" },
    { name: "Djibouti" },
    { name: "Dominica" },
    { name: "Dominican Republic" },
    { name: "Ecuador" },
    { name: "Egypt" },
    { name: "El Salvador" },
    { name: "Equatorial Guinea" },
    { name: "Eritrea" },
    { name: "Estonia" },
    { name: "Eswatini (fmr. \"Swaziland\")" },
    { name: "Ethiopia" },
    { name: "Fiji" },
    { name: "Finland" },
    { name: "France" },
    { name: "Gabon" },
    { name: "Gambia" },
    { name: "Georgia" },
    { name: "Germany" },
    { name: "Ghana" },
    { name: "Greece" },
    { name: "Grenada" },
    { name: "Guatemala" },
    { name: "Guinea" },
    { name: "Guinea-Bissau" },
    { name: "Guyana" },
    { name: "Haiti" },
    { name: "Holy See" },
    { name: "Honduras" },
    { name: "Hungary" },
    { name: "Iceland" },
    { name: "India" },
    { name: "Indonesia" },
    { name: "Iran" },
    { name: "Iraq" },
    { name: "Ireland" },
    { name: "Israel" },
    { name: "Italy" },
    { name: "Jamaica" },
    { name: "Japan" },
    { name: "Jordan" },
    { name: "Kazakhstan" },
    { name: "Kenya" },
    { name: "Kiribati" },
    { name: "Kuwait" },
    { name: "Kyrgyzstan" },
    { name: "Laos" },
    { name: "Latvia" },
    { name: "Lebanon" },
    { name: "Lesotho" },
    { name: "Liberia" },
    { name: "Libya" },
    { name: "Liechtenstein" },
    { name: "Lithuania" },
    { name: "Luxembourg" },
    { name: "Madagascar" },
    { name: "Malawi" },
    { name: "Malaysia" },
    { name: "Maldives" },
    { name: "Mali" },
    { name: "Malta" },
    { name: "Marshall Islands" },
    { name: "Mauritania" },
    { name: "Mauritius" },
    { name: "Mexico" },
    { name: "Micronesia" },
    { name: "Moldova" },
    { name: "Monaco" },
    { name: "Mongolia" },
    { name: "Montenegro" },
    { name: "Morocco" },
    { name: "Mozambique" },
    { name: "Myanmar (formerly Burma)" },
    { name: "Namibia" },
    { name: "Nauru" },
    { name: "Nepal" },
    { name: "Netherlands" },
    { name: "New Zealand" },
    { name: "Nicaragua" },
    { name: "Niger" },
    { name: "Nigeria" },
    { name: "North Korea" },
    { name: "North Macedonia" },
    { name: "Norway" },
    { name: "Oman" },
    { name: "Pakistan" },
    { name: "Palau" },
    { name: "Palestine State" },
    { name: "Panama" },
    { name: "Papua New Guinea" },
    { name: "Paraguay" },
    { name: "Peru" },
    { name: "Philippines" },
    { name: "Poland" },
    { name: "Portugal" },
    { name: "Qatar" },
    { name: "Romania" },
    { name: "Russia" },
    { name: "Rwanda" },
    { name: "Saint Kitts and Nevis" },
    { name: "Saint Lucia" },
    { name: "Saint Vincent and the Grenadines" },
    { name: "Samoa" },
    { name: "San Marino" },
    { name: "Sao Tome and Principe" },
    { name: "Saudi Arabia" },
    { name: "Senegal" },
    { name: "Serbia" },
    { name: "Seychelles" },
    { name: "Sierra Leone" },
    { name: "Singapore" },
    { name: "Slovakia" },
    { name: "Slovenia" },
    { name: "Solomon Islands" },
    { name: "Somalia" },
    { name: "South Africa" },
    { name: "South Korea" },
    { name: "South Sudan" },
    { name: "Spain" },
    { name: "Sri Lanka" },
    { name: "Sudan" },
    { name: "Suriname" },
    { name: "Sweden" },
    { name: "Switzerland" },
    { name: "Syria" },
    { name: "Tajikistan" },
    { name: "Tanzania" },
    { name: "Thailand" },
    { name: "Timor-Leste" },
    { name: "Togo" },
    { name: "Tonga" },
    { name: "Trinidad and Tobago" },
    { name: "Tunisia" },
    { name: "Turkey" },
    { name: "Turkmenistan" },
    { name: "Tuvalu" },
    { name: "Uganda" },
    { name: "Ukraine" },
    { name: "United Arab Emirates" },
    { name: "United Kingdom" },
    { name: "United States of America" },
    { name: "Uruguay" },
    { name: "Uzbekistan" },
    { name: "Vanuatu" },
    { name: "Venezuela" },
    { name: "Vietnam" },
    { name: "Yemen" },
    { name: "Zambia" },
    { name: "Zimbabwe"  }
]

export type CountrieKeys = keyof typeof countries[0];
export type Countries = typeof countries;
export type StatesKey = keyof typeof states[0];
export type States = typeof states;
